### ISSUE TITLE
iPadOS not supported

### ISSUE THREAD

**Issue by tristan-k** [aspenluxxxy/xenon#14] opened 2021-04-04 11:26 UTC
## Describe the bug

Clicking 'Pair Computer' and 'Add New Mount' does nothing.

## To Reproduce
1. Go to 'Settings'
2. Click on 'Xenon'
3. Click on 'Pair Computer'
4. Nothing happens

## Expected behavior
A window with the qr-code should appear.

## Screenshots
 https://user-images.githubusercontent.com/732025/113507085-bd3ce280-9548-11eb-85e8-370f0ef0849b.mov

## Setup (please complete the following information):
 - **iPadOS Version**: 14.3 on iPadPro (11 Inch 2020)
 - **Jailbreak used**: unc0ver 6.1.1

## Log
```
[ERROR] failed to read mounts.json: No such file or directory (os error 2)
[INFO] listening on port 28988
```

**Comment by aspenluxxxy** [comment] 2021-04-05 23:22
Duplicate of https://github.com/aspenluxxxy/xenon/issues/15, which will be fixed in Xenon 1.1.3.

**Closed by aspenluxxxy** 2021-04-05 23:22 UTC
Labels: bug
